# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
  
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-api-feed inaz/udagram-api-feed:v2
    - run: docker tag udagram-frontend:local inaz/udagram-frontend:v3
    - run: docker tag udagram-api-user inaz/udagram-api-user:v2
    - run: docker tag reverseproxy inaz/reverseproxy:v2
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker push inaz/udagram-api-feed:v2
    - run: docker push inaz/udagram-frontend:v3
    - run: docker push inaz/udagram-api-user:v2
    - run: docker push inaz/reverseproxy:v2
    

    
